[project]
name = "byte-common"
version = "0.2.0"
description = "Shared code package for all Byte Bot services"
authors = [
    { name = "Jacob Coffee", email = "jacob@z7x.org" },
]
dependencies = [
    "pydantic>=2.5.2",
    "pydantic-settings>=2.1.0",
    "sqlalchemy>=2.0.23",
    "advanced-alchemy>=0.6.1",
    "githubkit[auth-app] @ git+https://github.com/yanyongyu/githubkit.git",
    "python-dotenv>=1.0.0",
]
requires-python = ">=3.12,<4.0"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/byte_common"]
